spring:
  rabbitmq:
    host: 192.168.136.139
    port: 5672
    username: guest
    password: guest
  application:
    name: zuul-server
  redis:
    host: 192.168.136.139
server:
  port: 8088
env: dev
